# Database config
database:
  host: localhost
  port: 3306
  name: handleBigPostRequest
  user: admin
  pass: 1adphamnghia
  type: mysql


logs:
  LogGlobal: true
  PrintGlobal: true
  UseLogGlobalMode: true


