# Database config
database:
  host: localhost
  port: 3306
  name: handleBigPostRequest
  user: admin
  pass: 1adphamnghia
  type: mysql


mode:
  ModeRun: debug

logs:
  LogGlobal: false
  PrintGlobal: false
  UseLogGlobalMode: false

redis:
  host: localhost
  port: 6379
  pass:


